// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace Logic.CMS.ResourceCatalog
{
    public enum CatalogType
    {
        Default,
        Audio,
        Bonus,
        Cards,
        Clothes,
        Particles,
        UI,
        World,
    }
}
