using System;
using System.IO;
using System.Linq;
using System.Text;

using Sackrany.CMS.ResourceCatalog.ScriptableObjects;

using UnityEditor;

using UnityEngine;

namespace Sackrany.CMS.ResourceCatalog.Editor
{
    public static class CatalogEnumGenerator
    {
        private const string folderGeneratedPath = "Sackrany/Generated/HashCMS";

        public static void GenerateAll(CatalogObject catalogObject)
        {
            GenerateCatalogTypeEnums();
            GenerateHashEnums(catalogObject);
        }
        public static void GenerateCatalogTypeEnums()
        {
            string cmsDir = Path.Combine(Application.dataPath, "Resources/CMS/");
            if (!Directory.Exists(cmsDir))
                Directory.CreateDirectory(cmsDir);
    
            var dirs = Directory.GetDirectories(cmsDir, "*", SearchOption.AllDirectories)
                .Select(d => d.Replace("\\", "/"))
                .Select(d => d.Substring(d.IndexOf("CMS/", StringComparison.Ordinal) + 4))
                .Select(d => d.Replace("/", "_"))
                .Where(d => !string.IsNullOrWhiteSpace(d));

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace Sackrany.CMS");
            sb.AppendLine("{");
            sb.AppendLine("    public enum CatalogType");
            sb.AppendLine("    {");
            sb.AppendLine("        Default,");

            foreach (var dir in dirs)
            {
                string name = Sanitize(dir);
                sb.AppendLine($"        {name},");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            string fullDir = Path.Combine(Application.dataPath, folderGeneratedPath);
            if (!Directory.Exists(fullDir))
                Directory.CreateDirectory(fullDir);

            string fullPath = Path.Combine(fullDir, "CatalogType.cs");
            File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);
        }
        public static void GenerateHashEnums(CatalogObject catalogObject)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace Sackrany.CMS");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum HashCMS : uint");
            sb.AppendLine("    {");
            
            foreach (var catalog in catalogObject.Catalog)
            {
                foreach (var item in catalog.Objects)
                {
                    string name = Sanitize($"{catalog.Type.ToString()}_{item.Object.gameObject.name}");
                    uint hash = item.HashKey;
                    sb.AppendLine($"        {name} = {hash}u,");
                }
            }
                
            sb.AppendLine("    }");
            sb.AppendLine("}");

            string fullDir = Path.Combine(Application.dataPath, folderGeneratedPath);
            if (!Directory.Exists(fullDir))
                Directory.CreateDirectory(fullDir);
                
            string fullPath = Path.Combine(fullDir, $"HashCMS.cs");
            File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);
        }
        public static void ApplyGenerate()
        {
            AssetDatabase.Refresh();
        }
        
        private static string Sanitize(string s)
        {
            return System.Text.RegularExpressions.Regex.Replace(s, @"\W", "_");
        }
    }
}